# Generated by Django 4.1 on 2022-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0003_alter_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="done", field=models.BooleanField(default=False),
        ),
    ]
